services:
  selenium-test:
    build:
      dockerfile: Dockerfile
    container_name: selenium-test
    network_mode: "host" # Connect to the same network as the selenium grid
    environment:
      - SELENIUM_HUB_URL=http://localhost:4444/wd/hub
    command: > # Infinite loop so you can joing the running container
      bash -c "while true; do
        sleep 1
      done"